sudo: required

services:
  - docker

before_install:
  - docker pull ubuntu

script:
  - docker run ubuntu /bin/sh -c "cd /root/; curl https://github.com/wallento/newlib-travis/blob/master/build.sh; bash build.sh"
