sudo: required

services:
  - docker

before_install:
  - docker pull ubuntu
  - docker run ubuntu /bin/sh -c "mkdir /root/build; cd /root/build; git clone git@github.com:wallento/newlib-travis.git ."
  - docker run ubuntu /bin/sh -c "cd /root/build; ./setup.sh"

script:
  - docker run ubuntu /bin/sh -c "cd /root/build; ./build.sh"
